// Generates src/vscripts/boost/tooltip_data.ts: Dota's own tooltip label for every buffable ability value
// (e.g. necrolyte_heartstopper_aura|aura_damage -> "%Health decay"). The server uses it to tell which values Dota shows
// as a percentage (the label starts with "%") and what a value really is (a "health decay", not an "aura damage").
//
// Lua cannot read tooltips, so the labels come from the game UI: during `boost_audit_every` (tools mode, launched with
// npm run launch, which saves the console to dota 2 beta/game/dota/console.log) the UI prints one
// "[tooltip] ability|value|text" line per value. Run the audit in an English game client, then, from dota_boosted/:
//   node scripts/gen_tooltips.js
const fs = require("fs");
const path = require("path");
const { getDotaPath } = require("./utils");

/** "%HEALTH DECAY:" -> "%Health decay"; "+$damage BONUS:" -> "Damage bonus" (placeholders like $damage become words). */
function cleanLabel(raw) {
    let text = raw.trim();
    const percent = text.startsWith("%");
    if (percent) text = text.slice(1);
    text = text
        .replace(/<[^>]*>/g, "")
        .replace(/\$([A-Za-z_]+)/g, (_, word) => word.replace(/_/g, " "))
        .replace(/[+:：]/g, "")
        .replace(/\s+/g, " ")
        .trim()
        .toLowerCase();
    if (text === "") return undefined;
    return (percent ? "%" : "") + text.charAt(0).toUpperCase() + text.slice(1);
}

(async () => {
    const dotaPath = await getDotaPath();
    const consoleLog = path.join(dotaPath, "game", "dota", "console.log");
    const labels = new Map();
    for (const line of fs.readFileSync(consoleLog, "utf8").split(/\r?\n/)) {
        const at = line.indexOf("[tooltip] ");
        if (at < 0) continue;
        const [ability, value, ...rest] = line.slice(at + 10).split("|");
        const label = cleanLabel(rest.join("|"));
        // A later audit run wins over an earlier one in the same log
        if (ability && value && label !== undefined) labels.set(`${ability}|${value}`, label);
    }
    if (labels.size === 0) throw new Error("No [tooltip] lines in console.log: run boost_audit_every in game (tools mode) first.");

    const out = [...labels.keys()].sort().map(key => `    ${JSON.stringify(key)}: ${JSON.stringify(labels.get(key))},`);
    const target = path.resolve(__dirname, "..", "src", "vscripts", "boost", "tooltip_data.ts");
    fs.writeFileSync(
        target,
        [
            "// GENERATED by scripts/gen_tooltips.js from Dota's tooltips (boost_audit_every). Do not edit by hand: regenerate.",
            '// Keys are "ability|value"; a label starting with "%" is a value Dota shows as a percentage.',
            "export const tooltips: Record<string, string> = {",
            ...out,
            "};",
            "",
        ].join("\n"),
    );
    console.log(`${labels.size} tooltip labels written to ${target}`);
})().catch(error => {
    console.error(error);
    process.exit(1);
});
